# Generated by Django 3.2.13 on 2022-06-26 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('smallbusiness', models.BooleanField()),
                ('image', models.ImageField(upload_to='images/pieces')),
                ('link', models.CharField(max_length=5000)),
                ('description', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('origin_city', models.CharField(max_length=200)),
                ('origin_country', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('stone', models.CharField(max_length=200)),
            ],
        ),
    ]
